name: test

on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
      - next

jobs:
  test:
    name: Test - ${{ matrix.os }} - Node v${{ matrix.node-version }}, Webpack ${{ matrix.webpack-version }}

    strategy:
      matrix:
        os: [windows-latest]
        node-version: [10.x, 12.x, 13.x]
        webpack-version: [latest, next]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use latest NPM on ubuntu/macos
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: sudo npm i -g npm

      - name: Use latest NPM on windows
        if: matrix.os == 'windows-latest'
        run: npm i -g npm

      - name: Install dependencies
        run: npm ci

      - name: Install webpack ${{ matrix.webpack-version }}
        run: npm i webpack@${{ matrix.webpack-version }}

      - name: Run tests for webpack version ${{ matrix.webpack-version }}
        run: npm run test
